# Generated by Django 4.2.9 on 2024-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=200)),
                ('cheese', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=200)),
                ('table_number', models.IntegerField()),
                ('order_served', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
