# Generated by Django 4.2.9 on 2024-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_ordermodel_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_served',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
