# Generated by Django 4.2.9 on 2024-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_ordermodel_order_served_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='cheese',
            new_name='cheese_toppings',
        ),
    ]
