# Generated by Django 4.2.9 on 2024-01-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_cheese_ordermodel_cheese_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='cheese_toppings',
            new_name='cheese',
        ),
    ]
