# Generated by Django 4.2.9 on 2024-01-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_cheese_toppings_ordermodel_cheese'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=200)),
                ('cheese', models.CharField(max_length=200)),
                ('create_time', models.IntegerField()),
                ('customer_name', models.CharField(max_length=200)),
                ('table_number', models.IntegerField()),
                ('order_status', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
